services:
  mailserver:
    stdin_open: true
    tty: true
    restart: always
    container_name: simply-mailserver
    build:
      context: .
      args:
        DOMAIN_FQDN: ${DOMAIN_FQDN}
    env_file: .env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4000:4000" # front app
      - "4001:4001" # rspamd web interface
      - "4002:4002" # phpmyadmin
      - "4003:3000" # nest api
      - "4080:4080" # roundcube
      - "4190:4190" # to delete
      - "4443:4443" # roundcube
    extra_hosts:
      - "${DOMAIN_FQDN}:${ADRESSIP}"
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.200.0.5
    volumes:
      - ../volumes/log:/var/_log
      - ../volumes/ssl:/etc/_private
      - ../volumes/mail:/var/mail
      - ../volumes/mysql:/var/lib/mysql
      - ../volumes/postfix:/var/spool/postfix
      - ../volumes/postscreen:/etc/_postscreen
      - ../volumes/redis:/var/lib/redis
      - ../volumes/rspamd:/var/lib/rspamd
      - ../volumes/clamav:/var/lib/clamav
      - ../volumes/opendkim:/etc/opendkim
      - ../volumes/fail2ban:/var/lib/fail2ban

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.200.0.0/16"
          gateway: "172.200.0.1"
